import configparser, logging, asyncio, os, re
import google.generativeai as genai
from telegram import Bot
from telegram.constants import ParseMode
from telegram.error import TelegramError

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def get_pending_deals(filename="daily_deals.txt"):
    deals = []
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            for line in f:
                if '|||' in line:
                    deals.append(line.strip().split('|||', 1))
        return list(set(map(tuple, deals)))
    except FileNotFoundError:
        logging.info("No daily deals log file found. Nothing to summarize.")
        return []

def clear_daily_log(filename="daily_deals.txt"):
    try:
        if os.path.exists(filename):
            os.remove(filename)
            logging.info(f"Cleared '{filename}' for the next cycle.")
    except Exception as e:
        logging.error(f"Failed to clear daily log: {e}")

def sanitize_markdown_v2(text: str) -> str:
    escape_chars = r'_*[]()~`>#+-=|{}.!'
    return re.sub(f'([{re.escape(escape_chars)}])', r'\\\1', text)

async def get_summary_from_gemini(api_key, deals_data):
    genai.configure(api_key=api_key)
    model = genai.GenerativeModel('gemini-1.5-flash-latest')
    formatted_deals = "\n".join([f"Title: {title}\nURL: {url}" for url, title in deals_data])
    prompt = f"""
    You are the "Hoard-Watcher's Chronicler". Analyze the following list of game deal titles and their URLs. Generate a clean, concise summary digest in Telegram-compatible MarkdownV2 format.

    Your summary must have:
    1. A main title: *Daily Freebie Digest for [Today's Date]*.
    2. A brief, one-sentence overview highlighting the best deal(s).
    3. A bulleted list of the new free games. Each bullet point should be: `• *Game Title* on `Platform` ([Link](deal_url))`.
    4. You MUST infer the platform (Steam, Epic, GOG, etc.) from the title or URL.
    5. You MUST filter out junk like discussion threads, PSAs, DLC, and in-game loot. If no actual games are found, state that.

    Here is the data. Create the summary.

    --- DATA ---
    {formatted_deals}
    --- END DATA ---
    """
    try:
        logging.info("Sending request to Gemini API...")
        response = await model.generate_content_async(prompt)
        logging.info("Received response from Gemini API.")
        return response.text
    except Exception as e:
        logging.error(f"Error calling Gemini API: {e}")
        return "Failed to generate summary due to an API error."

async def send_telegram_message(bot_token, chat_id, message):
    try:
        bot = Bot(token=bot_token)
        sanitized_summary = sanitize_markdown_v2(message)
        final_message = sanitized_summary + "\n\n_This summary was automatically generated by the Hoard-Watcher's Chronicler\\._"
        await bot.send_message(chat_id=chat_id, text=final_message, parse_mode=ParseMode.MARKDOWN_V2)
        logging.info("Successfully sent summary to Telegram.")
    except TelegramError as e:
        logging.error(f"Telegram API Error after sanitizing: {e}")

async def main():
    logging.info("--- Summarizer Bot v3.1 Run Started ---")
    config = configparser.ConfigParser()
    config.read('config.ini')
    is_github_action = os.getenv('GITHUB_ACTIONS') == 'true'

    if is_github_action:
        telegram_token = os.getenv('TELEGRAM_TOKEN')
        chat_id = os.getenv('TELEGRAM_CHAT_ID')
        gemini_api_key = os.getenv('GEMINI_API_KEY')
    else:
        telegram_token = config['telegram']['token']
        chat_id = config['telegram']['chat_id']
        gemini_api_key = config['gemini']['api_key']

    if not all([telegram_token, chat_id, gemini_api_key]):
        logging.error("Required credentials missing. Aborting.")
        return

    log_file = "daily_deals.txt"
    pending_deals = get_pending_deals(log_file)
    
    if not pending_deals:
        logging.info("No new deals to summarize. Exiting.")
        return

    logging.info(f"Found {len(pending_deals)} unique deals to process.")
    summary_message = await get_summary_from_gemini(gemini_api_key, pending_deals)
    await send_telegram_message(telegram_token, chat_id, summary_message)
    clear_daily_log(log_file)
    logging.info("--- Summarizer Bot v3.1 Run Finished ---")

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())