name: Freebie-Finder Bot CI

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'

jobs:
  run-freebie-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # This step tries to restore the database from the last successful run
      - name: Restore freebies database cache
        uses: actions/cache@v4
        id: db-cache
        with:
          path: freebies.db
          # The key is simple, we always want the latest cache for the main branch
          key: ${{ runner.os }}-freebies-db-main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot_v2.py
        # The cache is automatically saved after the job completes if the key is new
        # or if the cache was restored and the job was successful.